In [1]:
#외부 모듈 선언
import turtle  #그래픽 처리를 위한 모듈 선언
import numpy as np  #벡터, 행렬 데이터를 쉽게 처리하기 위한 모듈 선언

In [2]:
pixelSize = 10  #pixel 사이즈의 반지름

In [3]:
turtle.speed(0)  #최고속도

In [4]:
def putPixel(x, y, pSize, pCol):
    turtle.penup()  #좌표 이동을 위해 펜기능을 비활성화
    turtle.goto(x*pSize, (-1)*y*pSize)  #주어진 좌표로 이동
    turtle.pendown()  #펜기능을 다시 활성화
    turtle.begin_fill()  #다각형을 그릴 때 내부를 채우기
    turtle.fillcolor(pCol)  #다각형의 채움색 결정하기
    turtle.setheading(45)  #시작 각도를 45도로 지정
    turtle.circle(pSize/2, steps = 4)  #정사각형 픽셀 도출하기
    turtle.end_fill()  #채우기 끝    

In [5]:
faceImg = np.array(
    [[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
    ,[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
    ,[0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0]
    ,[0,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0]
    ,[0,0,0,1,1,1,1,1,1,1,1,1,1,0,0,0]
    ,[0,0,0,1,1,1,1,1,1,1,1,1,1,0,0,0]
    ,[0,0,1,1,1,1,1,1,1,1,1,1,1,1,0,0]
    ,[0,0,1,1,1,1,1,1,1,1,1,1,1,1,0,0]
    ,[0,0,1,1,1,1,1,1,1,1,1,1,1,1,0,0]
    ,[0,0,1,1,1,1,1,1,1,1,1,1,1,1,0,0]
    ,[0,0,1,1,1,1,1,1,1,1,1,1,1,1,0,0]
    ,[0,0,0,1,1,1,1,1,1,1,1,1,1,0,0,0]
    ,[0,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0]
    ,[0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0]
    ,[0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0]
    ,[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
    ])

In [6]:
smileImg = np.array(
    [[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
    ,[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
    ,[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
    ,[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
    ,[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
    ,[0,0,0,0,0,2,2,0,0,2,2,0,0,0,0,0]
    ,[0,0,0,0,2,0,2,0,2,0,2,0,0,0,0,0]
    ,[0,0,0,0,2,2,2,0,2,2,2,0,0,0,0,0]
    ,[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
    ,[0,0,0,0,2,0,0,0,0,0,0,2,0,0,0,0]
    ,[0,0,0,0,2,2,0,0,0,0,2,2,0,0,0,0]
    ,[0,0,0,0,0,2,2,2,2,2,2,0,0,0,0,0]
    ,[0,0,0,0,0,0,2,2,2,2,0,0,0,0,0,0]
    ,[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
    ,[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
    ,[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
    ])

In [7]:
diffImage = np.array(faceImg - smileImg)  #faceImg 행렬과 smileImg 행렬의 차

In [8]:
print(diffImage)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  1  1  1  0  0  0  0  0  0]
 [ 0  0  0  0  1  1  1  1  1  1  1  1  0  0  0  0]
 [ 0  0  0  1  1  1  1  1  1  1  1  1  1  0  0  0]
 [ 0  0  0  1  1 -1 -1  1  1 -1 -1  1  1  0  0  0]
 [ 0  0  1  1 -1  1 -1  1 -1  1 -1  1  1  1  0  0]
 [ 0  0  1  1 -1 -1 -1  1 -1 -1 -1  1  1  1  0  0]
 [ 0  0  1  1  1  1  1  1  1  1  1  1  1  1  0  0]
 [ 0  0  1  1 -1  1  1  1  1  1  1 -1  1  1  0  0]
 [ 0  0  1  1 -1 -1  1  1  1  1 -1 -1  1  1  0  0]
 [ 0  0  0  1  1 -1 -1 -1 -1 -1 -1  1  1  0  0  0]
 [ 0  0  0  0  1  1 -1 -1 -1 -1  1  1  0  0  0  0]
 [ 0  0  0  0  0  1  1  1  1  1  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  1  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]


In [9]:
for j in range(0,16):
    for i in range(0,16):
        if(diffImage[j][i] > 0):
            putPixel(i,j,pixelSize,'orange')
        else:
            putPixel(i,j,pixelSize,'white')

In [10]:
turtle.exitonclick()